name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      go-version: "1.22.1"
    steps:
      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"
      - name: Export Go version
        run: echo "go-version=1.22.1" >> $GITHUB_ENV

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.setup.outputs.go-version }}

      - name: Build
        run: go build -v ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.setup.outputs.go-version }}

      - name: Test
        run: go test -coverprofile=coverage.out -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.setup.outputs.go-version }}

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

      - name: Run golangci-lint
        run: ./bin/golangci-lint run

  format:
    name: Format
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ needs.setup.outputs.go-version }}

      - name: Check formatting
        run: gofmt -d .
